/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quoteApp;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static quoteApp.ReadFromFile.fileDemoReader;
import static quoteApp.ReadFromFile.randomQuotePicker;

class AppTest {
    @Test
  void testRandomQuote()
    {
        String dataJson= fileDemoReader();
        Gson gson = new Gson();
        Quote[] quoteArray = gson.fromJson(dataJson , Quote[].class);
        Quote randomAns = randomQuotePicker(dataJson);
        boolean flag = false;

        for(Quote quote : quoteArray) {
            if(quote.toString().equals(randomAns.toString()))
            flag= true ;
        }

        assertTrue(flag);
    }


}
