/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quoteApp;

import com.google.gson.Gson;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Random;
import java.util.Scanner;

import static quoteApp.ReadFromFile.fileDemoReader;
import static quoteApp.ReadFromFile.randomQuotePicker;
import static quoteApp.ReadQuoteFromAPIAndSaveToFile.ReadQuoteFromAPI;


public class App {

    public static void main(String[] args) {

//        String dataJson= fileDemoReader();
//        Quote randomQuote = randomQuotePicker(dataJson);
//        System.out.println(randomQuote.toString());

        ReadQuoteFromAPI();


    }
}
